import antfu from '@antfu/eslint-config'

export default antfu({
  type: 'lib',
  formatters: true,
  pnpm: true,
  ignores: [
    '.bmad-core/**',
    '.claude/**',
    '**/**.md',
    '.cunzhi-memory/**',
    'docs/docs/sdk/**',
    'html/assets/**',
    'dist/**',
  ],
  rules: {
    'no-console': 'off',
    'node/prefer-global/process': 'off',
    'node/prefer-global/buffer': 'off',
    'ts/explicit-function-return-type': 'off',
    'no-template-curly-in-string': 'off',
    'ts/no-require-imports': 'off',
    'regexp/no-unused-capturing-group': 'off',
    'regexp/no-super-linear-backtracking': 'off',
    'regexp/no-dupe-disjunctions': 'off',
    'regexp/optimal-quantifier-concatenation': 'off',
    'jsdoc/check-param-names': 'off',
    'no-control-regex': 'off',
    'unicorn/prefer-number-properties': 'off',
    'antfu/no-top-level-await': 'off',
    'no-prototype-builtins': 'off',
    'pnpm/yaml-no-unused-catalog-item': 'off',
    'pnpm/yaml-no-duplicate-catalog-item': 'off',
    'no-case-declarations': 'off',
    'no-cond-assign': 'off',
    'style/no-mixed-operators': 'off',
    'ts/no-unused-expressions': 'off',
    'no-restricted-globals': 'off',
    'style/max-statements-per-line': 'off',
    'no-new': 'off',
    'unicorn/no-new-array': 'off',
    'ts/no-use-before-define': 'off',
    'no-throw-literal': 'off',
    'yaml/sort-keys': 'off',
    'valid-typeof': 'off',
    'ts/no-this-alias': 'off',
    'ts/method-signature-style': 'off',
    'regexp/no-misleading-capturing-group': 'off',
    'node/handle-callback-err': 'off',
    'no-fallthrough': 'off',
    'no-eval': 'off',
    'import/no-mutable-exports': 'off',
    'jsonc/no-dupe-keys': 'off',
    'prefer-const': 'off',
    'typescript-eslint/no-require-imports': 'off',
    'unused-imports/no-unused-vars': ['error', {
      args: 'after-used',
      argsIgnorePattern: '^_',
      varsIgnorePattern: '^_',
      caughtErrors: 'all',
      caughtErrorsIgnorePattern: '^_',
    }],
  },
})
