packages:
  - .
  - docs

catalog:
  '@antfu/eslint-config': ^5.4.1
  '@anthropic-ai/sdk': ^0.52.0
  '@changesets/cli': ^2.29.7
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@commitlint/types': ^20.3.1
  '@iconify-json/carbon': ^1.2.14
  '@types/fs-extra': ^11.0.4
  '@types/inquirer': ^9.0.9
  '@types/node': ^22.18.6
  '@typescript-eslint/eslint-plugin': ^6.0.0
  '@typescript-eslint/parser': ^6.0.0
  '@unocss/reset': ^66.5.9
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  ansis: ^4.1.0
  cac: ^6.7.14
  chokidar: ^4.0.3
  dayjs: ^1.11.18
  eslint: ^9.36.0
  eslint-plugin-format: ^1.0.2
  find-up-simple: ^1.0.1
  fs-extra: ^11.3.2
  glob: ^11.0.3
  gray-matter: ^4.0.3
  husky: ^9.1.7
  i18next: ^25.5.2
  i18next-fs-backend: ^2.6.0
  inquirer: ^12.9.6
  inquirer-toggle: ^1.0.1
  lint-staged: ^16.2.0
  nanoid: ^5.1.6
  ora: ^9.0.0
  pathe: ^2.0.3
  prettier: ^3.0.0
  semver: ^7.7.2
  smol-toml: ^1.4.2
  tar: ^7.5.2
  tinyexec: ^1.0.1
  trash: ^10.0.0
  tsx: ^4.20.5
  typescript: ^5.9.2
  unbuild: ^3.6.1
  unocss: ^66.5.9
  vitepress: ^1.6.4
  vitest: ^3.2.4
  vue: ^3.5.25

catalogs:
  conflicts_@types/node_h20_11_5:
    '@types/node': ^20.11.5
  conflicts_conflicts_@types/node_h20_11_5_h22_18_6:
    '@types/node': ^22.18.6
  conflicts_conflicts_tsx_h4_7_2_h4_20_5:
    tsx: ^4.20.5
  conflicts_conflicts_typescript_h5_3_3_h5_9_2:
    typescript: ^5.9.2
  conflicts_tsx_h4_7_2:
    tsx: ^4.7.2
  conflicts_typescript_h5_3_3:
    typescript: ^5.3.3

onlyBuiltDependencies:
  - esbuild
