/**
 * ShenCha (审查) - LLM-Driven Autonomous Code Audit System Types
 */

/**
 * Project context for LLM analysis
 */
export interface ProjectContext {
  /** Project root path */
  rootPath: string
  /** Detected language/framework */
  framework?: string
  /** Package manager */
  packageManager?: 'npm' | 'yarn' | 'pnpm' | 'bun'
  /** Source directories */
  sourceDirs: string[]
  /** Test directories */
  testDirs: string[]
  /** Configuration files */
  configFiles: string[]
  /** Git information */
  git?: {
    branch: string
    lastCommit: string
    uncommittedChanges: number
  }
}

/**
 * Scan target discovered by LLM
 */
export interface ScanTarget {
  /** Target type */
  type: 'file' | 'directory' | 'function' | 'class' | 'module' | 'api' | 'config'
  /** Target path */
  path: string
  /** Reason for scanning */
  reason: string
  /** Priority (1-10, 10 being highest) */
  priority: number
  /** Estimated complexity */
  complexity: 'low' | 'medium' | 'high'
  /** Tags for categorization */
  tags: string[]
}

/**
 * Scan strategy determined by LLM
 */
export interface ScanStrategy {
  /** Strategy type */
  type: 'security' | 'performance' | 'quality' | 'accessibility' | 'comprehensive'
  /** Specific checks to perform */
  checks: string[]
  /** Depth of analysis */
  depth: 'surface' | 'moderate' | 'deep'
  /** Context to include */
  contextFiles: string[]
  /** LLM model to use */
  model: 'opus' | 'sonnet' | 'haiku'
}

/**
 * Scan result from LLM analysis
 */
export interface ScanResult {
  /** Target that was scanned */
  target: ScanTarget
  /** Strategy used */
  strategy: ScanStrategy
  /** Timestamp */
  timestamp: Date
  /** Duration in milliseconds */
  duration: number
  /** Issues found */
  issues: Issue[]
  /** Metrics collected */
  metrics: Record<string, number>
  /** LLM reasoning/notes */
  notes: string
}

/**
 * Issue found during scan
 */
export interface Issue {
  /** Issue unique ID */
  id: string
  /** Issue title */
  title: string
  /** Detailed description */
  description: string
  /** Severity level */
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info'
  /** Issue category */
  category: 'security' | 'performance' | 'quality' | 'style' | 'accessibility' | 'logic'
  /** File path */
  file: string
  /** Line number (if applicable) */
  line?: number
  /** Column number (if applicable) */
  column?: number
  /** Code snippet */
  snippet?: string
  /** Suggested fix */
  suggestedFix?: string
  /** Whether auto-fix is safe */
  autoFixable: boolean
  /** Related issues */
  relatedIssues?: string[]
  /** Confidence score (0-1) */
  confidence: number
}

/**
 * Evaluated issue with LLM decision
 */
export interface EvaluatedIssue extends Issue {
  /** LLM evaluation reasoning */
  evaluation: string
  /** Actual priority (may differ from severity) */
  priority: number
  /** Recommended action */
  action: 'fix-now' | 'fix-later' | 'monitor' | 'ignore'
  /** Effort estimate */
  effort: 'trivial' | 'small' | 'medium' | 'large'
}

/**
 * Fix decision from LLM
 */
export interface FixDecision {
  /** Whether to auto-fix */
  shouldFix: boolean
  /** Reasoning */
  reason: string
  /** Risk assessment */
  risk: 'none' | 'low' | 'medium' | 'high'
  /** Prerequisites before fixing */
  prerequisites: string[]
  /** Post-fix verification steps */
  verificationSteps: string[]
}

/**
 * Fix plan generated by LLM
 */
export interface FixPlan {
  /** Issue being fixed */
  issueId: string
  /** Approach description */
  approach: string
  /** Files to modify */
  filesToModify: string[]
  /** Expected changes description */
  expectedChanges: string
  /** Rollback strategy */
  rollbackStrategy: string
  /** Tests to run after fix */
  testsToRun: string[]
}

/**
 * Generated fix from LLM
 */
export interface GeneratedFix {
  /** Plan used */
  plan: FixPlan
  /** File changes */
  changes: FileChange[]
  /** Commit message */
  commitMessage: string
  /** Timestamp */
  generatedAt: Date
}

/**
 * File change in a fix
 */
export interface FileChange {
  /** File path */
  path: string
  /** Change type */
  type: 'modify' | 'create' | 'delete' | 'rename'
  /** Original content (for modify/delete) */
  originalContent?: string
  /** New content (for modify/create) */
  newContent?: string
  /** New path (for rename) */
  newPath?: string
  /** Diff (unified format) */
  diff?: string
}

/**
 * Fix application result
 */
export interface FixResult {
  /** Fix that was applied */
  fix: GeneratedFix
  /** Success status */
  success: boolean
  /** Applied changes */
  appliedChanges: FileChange[]
  /** Failed changes */
  failedChanges: Array<{ change: FileChange, error: string }>
  /** Backup paths */
  backupPaths: string[]
  /** Timestamp */
  appliedAt: Date
}

/**
 * Verification result from LLM
 */
export interface VerifyResult {
  /** Fix that was verified */
  fix: GeneratedFix
  /** Overall success */
  success: boolean
  /** Code correctness verified */
  codeCorrect: boolean
  /** No regressions detected */
  noRegressions: boolean
  /** No new issues introduced */
  noNewIssues: boolean
  /** Verification notes */
  notes: string
  /** Recommendations */
  recommendations: string[]
}

/**
 * Regression found during verification
 */
export interface Regression {
  /** Type of regression */
  type: 'functional' | 'performance' | 'breaking-change'
  /** Description */
  description: string
  /** Affected files */
  affectedFiles: string[]
  /** Severity */
  severity: 'critical' | 'high' | 'medium' | 'low'
}

/**
 * New issue introduced by fix
 */
export interface NewIssue extends Issue {
  /** The fix that introduced this issue */
  introducedByFix: string
}

/**
 * Execution plan for async audit
 */
export interface ExecutionPlan {
  /** Plan ID */
  id: string
  /** Creation timestamp */
  createdAt: Date
  /** Targets to scan */
  targets: ScanTarget[]
  /** Execution order */
  order: string[]
  /** Parallel execution groups */
  parallelGroups: string[][]
  /** Estimated duration */
  estimatedDuration: number
  /** Priority queue */
  priorityQueue: Array<{ targetId: string, priority: number }>
}

/**
 * ShenCha configuration
 */
export interface ShenChaConfig {
  /** Schedule configuration */
  schedule: {
    intervalHours: number
    totalDurationHours: number
    startTime?: string
  }
  /** LLM configuration */
  llm: {
    baseUrl: string
    apiKey?: string
    models: {
      scanning: string
      analysis: string
      fixing: string
    }
    maxTokens?: number
    temperature?: number
  }
  /** Scanner configuration */
  scanners: {
    page?: { enabled: boolean, criticalPages?: string[] }
    api?: { enabled: boolean, endpoints?: string[] }
    errorLog?: { enabled: boolean, lookbackHours?: number }
    userBehavior?: { enabled: boolean, database?: string }
  }
  /** Fixer configuration */
  fixer: {
    enabled: boolean
    autoCommit: boolean
    safetyChecks: {
      requireTypeCheck: boolean
      requireLintPass: boolean
      requireTestPass: boolean
      maxFilesPerFix: number
      maxLineChanges: number
      requireReview: string[]
    }
  }
  /** Reporter configuration */
  reporter: {
    outputDir: string
    formats: Array<'markdown' | 'json' | 'html'>
    webhooks?: Array<{ url: string, events: string[] }>
  }
}

/**
 * Audit cycle status
 */
export interface AuditCycleStatus {
  /** Cycle number */
  cycleNumber: number
  /** Total cycles planned */
  totalCycles: number
  /** Current status */
  status: 'pending' | 'scanning' | 'analyzing' | 'fixing' | 'verifying' | 'completed' | 'failed'
  /** Start time */
  startedAt?: Date
  /** End time */
  completedAt?: Date
  /** Issues found this cycle */
  issuesFound: number
  /** Issues fixed this cycle */
  issuesFixed: number
  /** Current target being processed */
  currentTarget?: string
  /** Progress percentage */
  progress: number
}

/**
 * Audit report
 */
export interface AuditReport {
  /** Report ID */
  id: string
  /** Cycle number */
  cycleNumber: number
  /** Generation timestamp */
  generatedAt: Date
  /** Duration */
  duration: number
  /** Summary */
  summary: {
    totalIssues: number
    fixedIssues: number
    pendingIssues: number
    scores: {
      security: number
      performance: number
      quality: number
    }
  }
  /** Issues by category */
  issuesByCategory: Record<string, Issue[]>
  /** Fixes applied */
  fixesApplied: FixResult[]
  /** Recommendations */
  recommendations: string[]
  /** Next steps */
  nextSteps: string[]
}
