/**
 * Main entry point for the entire package
 */

export * from './code-tools'
export * from './utils'
export * from './analyzers'

// Export cloud-client with explicit re-exports to avoid conflicts
export {
  CachedCloudClient,
  CloudCache,
  CloudClient,
  CloudError,
  CloudErrorCode,
  CloudErrorFactory,
  FallbackCloudClient,
  RatingsApiError,
  RatingsApiErrorCode,
  RetryableCloudClient,
  TelemetryReporter,
  TemplatesClient,
  canInstallMore,
  convertBatchTemplateResponse,
  convertConfig,
  convertParameterDefault,
  convertProjectAnalysisResponse,
  convertRecommendation,
  convertTemplate,
  convertTemplateParameter,
  createCloudClient,
  createCompleteCloudClient,
  createRating,
  createTemplatesClient,
  formatErrorForLogging,
  getCloudMcpRecommendations,
  getCloudRecommendations,
  getCloudRecommendedHooks,
  getCloudSkillRecommendations,
  getCommunityHooks,
  getDisabledSkills,
  getEnabledSkills,
  getQuotaUsagePercentage,
  getRecommendations,
  getRetryDelay,
  getSkillRatings,
  getTelemetry,
  getTemplatesClient,
  getUserQuota,
  getUserSkills,
  handleCloudError,
  initializeTelemetry,
  installSkill,
  isAuthError,
  isDuplicateRatingError,
  isRateLimitError,
  isRecommendationConfig,
  isRetryableError,
  isRetryableErrorCode,
  isSkillInstalled,
  isSkillNotFoundError,
  isTelemetryEventData,
  isTemplateParameterValue,
  isUnauthorizedError,
  ratingsApi,
  retryUtils,
  skillsMarketplaceApi,
  sortByLastUsed,
  sortByUsage,
  stopTelemetry,
  submitHookAnalytics,
  telemetryUtils,
  trackEvent,
  uninstallSkill,
  updateSkill,
  userSkillsApi,
  validateBatchTemplateRequest,
  validateProjectAnalysisRequest,
  validateUsageReport,
  withRetry,
} from './cloud-client'

export type {
  AgentConfig,
  AnalysisCompletedData,
  AuthRequestOptions,
  BatchTelemetryData,
  BatchTemplateRequest,
  BatchTemplateResponse,
  CacheEntry,
  CloudClientError,
  CloudErrorMetadata,
  CreateRatingData,
  CreateRatingResponse,
  ErrorOccurredData,
  GetSkillRatingsParams,
  GetSkillRatingsResponse,
  HealthCheckResponse,
  HookConfig,
  McpServerConfig,
  MetricType,
  ProjectAnalysisRequest,
  ProjectAnalysisResponse,
  RatingSortOption,
  RawBatchTemplateResponse,
  RawProjectAnalysisResponse,
  RawRecommendation,
  RawTemplate,
  Recommendation,
  RecommendationAcceptedData,
  RecommendationConfig,
  RecommendationShownData,
  SkillConfig,
  TelemetryEventData,
  TemplateDownloadData,
  TemplateParameter,
  TemplateParameterValue,
  TemplateResponse,
  TemplateType,
  UsageReport,
  UsageReportResponse,
  WorkflowConfig,
} from './cloud-client'
